---
rplidar_node:
  ros__parameters:
    serial_port: "/dev/ttyUSB1" # đổi theo cổng thực tế (vd: /dev/ttyUSB1)
    baudrate: 460800 
    frame_id: "lidar_link"
    scan_topic: "/scan"
    cloud_topic: "/scan_cloud"
    publish_cloud: true 
    angle_compensate: true
    range_min: 0.15
    range_max: 12.0
    angle_min_deg: 0.0
    angle_max_deg: 360.0
    angle_increment_deg: 0.5  # 0.5–1.0 là hợp lý; nhỏ quá sẽ nặng CPU
    publish_cloud: true # tắt nếu không cần PointCloud2
